name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build wheel setuptools
        python -m pip install -r requirements.txt
    - name: build package
      run: python -m build
    - name: upload package
      uses: actions/upload-artifact@v3
      with:
       name: final_idp_utilities_david_hdez
       path: dist/

  release:
    runs-on: ubuntu-latest
    
    needs: build
    
    permissions:
      contents: write
      id-token: write
      
    steps:

    - name: download package
      uses: actions/download-artifact@v3
      with:
        name: final_idp_utilities_david_hdez 
        path: dist/

    - name: sign package
      uses: sigstore/gh-action-sigstore-python@v1.2.3
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Get previous version
      id: prevtag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1.4.0'
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Get next version
      id: nexttag
      uses: 'WyriHaximus/github-action-next-release-version@v1'
      with:
        version: ${{ setps.prevtag.outputs.tag }}

    - name: github Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release create '${{ steps.nexttag.outputs.version }}' --repo '${{ github.repository }}' --notes ""

    - name: Upload signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release upload '${{ steps.nexttag.outputs.version }}' dist/** --repo '${{ github.repository }}'
